name: Stdlib stubtest

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "stdlib/**"
      - ".github/workflows/stubtest_stdlib.yml"
      - "tests/**"
      # When requirements.txt changes, we run `daily.yml`, which includes stdlib stubtest

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1
  TERM: xterm-256color # needed for FORCE_COLOR to work on mypy on Ubuntu, see https://github.com/python/mypy/issues/13817

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  stubtest-stdlib:
    name: "stubtest: stdlib"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements-tests.txt
          allow-prereleases: true
          check-latest: true
      - name: Install dependencies
        run: pip install -r requirements-tests.txt
      - name: Run stubtest
        run: python tests/stubtest_stdlib.py

  stubtest-stdlib-other-platforms:
    name: "stubtest: stdlib"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        os: ["freebsd-15.0", "openbsd-7.8", "solaris-11.4"]

    steps:
      - uses: actions/checkout@v5
      - name: Run stubtest on ${{ matrix.os }}
        uses: vmactions/freebsd-vm@v1
        if: ${{ matrix.os == "freebsd-15.0" }}
        with:
          release: "15.0"
          usesh: true
          prepare: |
            pkg install -y python311 py311-pip
          run: |
            pip install -r requirements-tests.txt
            python3.11 tests/stubtest_stdlib.py

      - name: Run stubtest on ${{ matrix.os }}
        uses: vmactions/openbsd-vm@v1
        if: ${{ matrix.os == "openbsd-7.8" }}
        with:
          release: "7.8"
          usesh: true
          prepare: |
            pkg_add python312 py312-pip
          run: |
            pip install -r requirements-tests.txt
            python3 tests/stubtest_stdlib.py

      - name: Run stubtest on ${{ matrix.os }}
        uses: vmactions/solaris-vm@v1
        if: ${{ matrix.os == "solaris-11.4" }}
        with:
          release: "11.4"
          usesh: true
          prepare: |
            pkgutil -y -i python312 py312-pip
          run: |
            pip install -r requirements-tests.txt
            python3 tests/stubtest_stdlib.py
